language: node_js
node_js:
  - 8
  - 10

before_install:
# package-lock.json was introduced in npm@5
- npm install -g npm@5
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script:
  - npm run lint
  - npm run cover
  - npm run coveralls
  - npm t
